### PR TITLE
WIP: Keepass import

### LINKED ISSUE #120: Import from KeePass
Add a menu option to import from a keepass archive.

### PR DESCRIPTION
**Pull request by perry-mitchell**
Add support for importing keepass archives.
Closes #120

### CODE REVIEW

**Comment by perry-mitchell** [comment]
Hey mate, could you check this out when you get time? 😄

**Comment by sallar** [comment]
@perry-mitchell I have added the password prompt which asks for the archive password before importing. There is one issue, if the password is wrong, the KeePass importer doesn't throw an error or reject a promise, so my "dialog" that says an error has occurred never fires... I think this needs to be fixed in `buttercup-importer` repo.

**Comment by perry-mitchell** [comment]
So all fixed. Is this good to go @sallar ?

**Comment by sallar** [comment]
@perry-mitchell Good to go! 👍

**Pull request merged**
