### PR TITLE
WIP: Reactify

### LINKED ISSUE #89: Allow clicking on the arrow icon of a Group
My instinct is to click the arrow icon of a group to expand it's contents.

buttercup-arrows

### PR DESCRIPTION
**Pull request by sallar**
🔥 
This is work in progress. **PLEASE DO NOT MERGE**.
Closes #89, #80, #79, #77, #75, #58, #34, #33, #20, #15, #49, #82, #90, #1, #60, #76, #91 

Project management here:
https://github.com/buttercup-pw/buttercup/projects/1

- [x] New Archive from File
  - [x] Password Entry
- [x] Open Archive File
  - [x] Password Entry
- [x] Group Tree
  - [x] Add
  - [x] Delete
  - [x] Move
  - [x] Drag/Drop
- [x] Entries List
- [x] Entry
  - [x] View
  - [x] Edit
  - [x] Delete
  - [x] New
  - [x] Move to Group
- [x] UI
  - [x] Intro Screen
  - [x] Tree Column
  - [x] Entries Column
  - [x] Entry Viewer / Editor
  - [x] Resizable Columns
- [x] App
  - [x] New/Open/New Window Menu Items
  - [x] `rpc` improvement
  - [x] Better window management
- [x] Release
  - [x] Build
  - [x] Package
  - [x] Installers
  - [ ] ~`.bcup` Assosciation~ (postponed)
  - [ ] ~Auto Update~ (postponed)

### CODE REVIEW

**Comment by perry-mitchell** [comment]
Due to the core being updated, this also fixes #48

**Comment by Jameskmonger** [comment]
@sallar may I ask why you have raised a PR for this if it's not ready for merge? Not that I have an issue - just curious!

**Comment by perry-mitchell** [comment]
IMHO it's pretty commonplace to have long-running PRs for a number of reasons. It makes it easier for others to follow the changes and progress, rather than just looking at a branch. A PR keeps the status of a project in a more visible location. I like seeing the issues it affects (closes) and if there were tests, we could see the stability of the work as well.

Just my two cents 😄

**Comment by sallar** [comment]
@Jameskmonger Like @perry-mitchell mentioned it’s a common practice that is done usually for visibility and better understanding of the process. Also, code reviews, comments and suggestions are easier to do in this phase. Cheers!

**Comment by Jameskmonger** [comment]
Makes sense to me! Thanks for explaining!

**Pull request merged**
